### ISSUE TITLE
S3 docker exited when error happens.

### ISSUE THREAD

**Issue by sfzeng** [sodafoundation/multi-cloud#1031]
**Issue/Feature Description:**
When an request arrived at s3 service, and it encountered an error then it will exit. At the same time,  when s3_api start, we can see the warning:
![protobuf_warn](https://user-images.githubusercontent.com/38932432/85403114-6b196a80-b58f-11ea-886a-e2ead0ce2634.png)

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
s3 docker should not exit when a non-critical error happens.

**How to reproduce, in case of a bug:**
1. Register a backend with wrong ak/sk.
2. Create a bucket using this backend as it's default backend.
3. Upload an object to the bucket.
Then you will see the s3 docker exited.

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by PravinRanjan10** [comment]
Please test first and then close
