### ISSUE TITLE
AWS Block Driver Support

### ISSUE THREAD

**Issue by himanshuvar** [sodafoundation/multi-cloud#1038]
**Issue/Feature Description:**
Implement AWS block driver for AWS Volume

**Why this issue to fixed / feature is needed(give scenarios or use cases):** Bock Driver for AWS

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by kumarashit** [comment]
The Block driver support is already added. Enhancements and new APIs will be tracked under new issues
