### ISSUE TITLE
Add UTs and Code coverage as part of CI

### ISSUE THREAD

**Issue by kumarashit** [sodafoundation/multi-cloud#1057]
**Issue/Feature Description:**
Current CI for multi-cloud is simply build the components. It should actually encompass UTs, coverage and automation
**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by rajat-soda** [comment]
Subtasks : 
   - Create UTs for multi-cloud/file
   - Create UTs for multi-cloud/block
   - Create UTs for multi-cloud/backend
