### ISSUE TITLE
Documentation issue in Multi-cloud Local Cluster Installation and Testing

### ISSUE THREAD

**Issue by vineela1999** [sodafoundation/multi-cloud#1069]
**Issue/Feature Description:**
https://github.com/sodafoundation/multi-cloud/blob/master/docs/installation_and_testing.md
In the above link ,
In Golang installation step there is a mismatch in GO versions in wget and tar commands 
Also incomplete mkdir command is mentioned.

wget https://storage.googleapis.com/golang/go**1.11.2**.linux-amd64.tar.gz
tar -C /usr/local -xzf go**1.13.9**.linux-amd64.tar.gz
**mkdir**  
This need to be updated in the document.

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by skdwriting** [comment]
@vineela1999 can we close this?
