### ISSUE TITLE
[UI REFRESH] : Refresh on any submenu page shows the Home Page.

### ISSUE THREAD

**Issue by rajat-soda** [sodafoundation/multi-cloud#1127]
**Issue/Feature Description:**
If the user refreshes on any Volume/ Resouce page , the home page is shown. 

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Context switch between pages should not happen on a page refresh. 

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by himanshuvar** [comment]
@rajat-soda Can you move this Issue to Dashboard

**Comment by anvithks** [comment]
@rajat-soda This is a known issue  in Dashboard. [dashboard/issues/153](https://github.com/sodafoundation/dashboard/issues/153)

**Comment by anvithks** [comment]
This issue can be closed here. @rajat-soda @himanshuvar

**Comment by kumarashit** [comment]
Closing as per previous comments
