### ISSUE TITLE
Hetrogenous Object Storage

### ISSUE THREAD

**Issue by kumarashit** [sodafoundation/multi-cloud#1166]
**Issue/Feature Description:**
Umbrella issue for all the tasks related to **Heterogeneous Object Storage**

Tasks:

- [ ] Bucket Managment Feature (All supported vendors and ceph)
- [ ] SODA Multicloud HA and load balancer delivery
- [ ] User Management  (Object focus) Development

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
To support the Heterogeneous Object Storage requirements

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by rajat-soda** [comment]
Implemented in Isabela Release
