### ISSUE TITLE
HOS : Create Bucket AWS 

### ISSUE THREAD

**Issue by rajat-soda** [sodafoundation/multi-cloud#1167]
**Issue/Feature Description:**
HOS : Create Bucket AWS 

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Create bucket from SODA , use-case of Bucket creation and placement in a Storage Tier.

**How to reproduce, in case of a bug:**
Not available from SODA 

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by kumarashit** [comment]
Facing auth issue.
Will try to fix by 15/022021

**Comment by rajat-soda** [comment]
Bucket Creation and Delete is done, other operation is WIP.
