### ISSUE TITLE
HOS : SODA Bucket / Object Storage Lifecycle - Sanity. GCP

### ISSUE THREAD

**Issue by rajat-soda** [sodafoundation/multi-cloud#1179]
**Issue/Feature Description:**
Sanity of Object Liefcycle for:

- [x] AWS
- [ ] GCP
- [x] Azure

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by kumarashit** [comment]
Feature completed
