### ISSUE TITLE
Bucket Management APIs for different cloud providers

### ISSUE THREAD

**Issue by kumarashit** [sodafoundation/multi-cloud#1186]
**Issue/Feature Description:**
Implement CRUD API for bucket management in different cloud backend

- [x] Create API for AWS
- [x] Create API for Azure
- [x] Create API for GCP
- [x] Update API for AWS
- [x] Update API for Azure
- [x] Update API for GCP
- [x] Read API for AWS
- [x] Read API for Azure
- [x] Read API for GCP
- [x] Delete API for AWS
- [x] Delete API for Azure
- [x] Delete API for GCP

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Support new bucket management in multi-cloud

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by rajat-soda** [comment]
Scope for Iteration-2 : [] Create Bucket

**Comment by rajat-soda** [comment]
Implemented in Isabela Release
