### ISSUE TITLE
Fix review comments for multicloud-ha

### ISSUE THREAD

**Issue by rajat-soda** [sodafoundation/multi-cloud#1202]
**Issue/Feature Description:**
- IMHO Sensitive info like username and password should be stored in Secrets.
Ref: https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

- The mount can be ignore by using kubernetes logging pipeline

- we can apply multiple resources in a directory and sub directory by
kubectl apply -f <directory> --recursive

- I think its not good choice to provide additional privileges to default service account.
A good choice would be to create a namespace , add a service account and give access to that service account.
Also same Service account need to be get used for add deployment of application trying to access kubernetes APIs by github.com/micro/go-plugins/registry/kubernetes/v2

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by AmitRoushan** [comment]
One missing comments:
- Generally each most of solution deployment create its own namespace in kubernetes and deploy all resources in it.
   Advantages:
   - Avoid resource name conflicts
   - If required, Namespace can be deleted to recursively delete all resources in it
   
   I believe second pointer could be used here

**Comment by AmitRoushan** [comment]
update:

Yaml can be optimized by adding namespace attribute.

review comment in #1210
