### ISSUE TITLE
Fix services dependencies in docker-compose.yaml for deployment 

### ISSUE THREAD

**Issue by AmitRoushan** [sodafoundation/multi-cloud#1237]
**Issue/Feature Description:**
Gelato installation is failing randomly because of interdependencies of service not handled in docker compose.

![Installation Issue - Dependencies not defined](https://user-images.githubusercontent.com/9818606/113250787-c9be0280-92de-11eb-855e-f4fd4895905c.JPG)

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
The issue is raised to handle smooth and fail safe deployment of gelato services with docker-compose.

**How to reproduce, in case of a bug:**
The issue is random as it depends on order of services getting deployed by docker-compose. 

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**
Note:
The fix is to add:
1. Inter dependencies of services over one other. Use ```depends_on``` feature in docker-compose
2. Add restart policy for each services. It adds up reliability as well.

**Comment by PravinRanjan10** [comment]
Fixed. Closing
