### ISSUE TITLE
Bucket Tier[DELETE]: API to delete created tier policy

### ISSUE THREAD

**Issue by PravinRanjan10** [sodafoundation/multi-cloud#1260]
**Issue/Feature Description:**

As a admin, I want to delete created tier policy.

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by vineela1999** [comment]
An empty tier(with no backends) can be deleted

DELETE http://IP:PORT/v1/tenantId/tiers/tierId
Request Body:
NA

Response:
Return Code: integer, Ex:200

Message: string, Ex: Successfully Deleted!
