### ISSUE TITLE
Bucket Tier[GET]: API to list all created tier policy

### ISSUE THREAD

**Issue by PravinRanjan10** [sodafoundation/multi-cloud#1261]
**Issue/Feature Description:**

As a admin/user, I want to list down all available tier policy

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by vineela1999** [comment]
**List all Tiers:**
GET http://IP:PORT/v1/tenantId/tiers
Request Body:
N/A

Response:
ReturnCode: integer, Ex:200

Message: [], Ex: [Gold]

**Get Tier:**
GET http://IP:PORT/v1/tenantId/tiers/tierId
Request Body:
N/A

Response:
ReturnCode: integer, Ex:200
Message: json
