### ISSUE TITLE
[Bucket Tier]Implementation of Selection Service for Bucket Tiering

### ISSUE THREAD

**Issue by PravinRanjan10** [sodafoundation/multi-cloud#1267]
**Issue/Feature Description:**
1. One the policy are selected by users, how backends are selected using this policy should be implemented

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by rajat-soda** [comment]
Link the design doc specific to this implementation

**Comment by rajat-soda** [comment]
Started work on this. 
Minimum Viable Policy Selection targeted for J Rel.
