### ISSUE TITLE
Optimization of Tier CRUD API and validations

### ISSUE THREAD

**Issue by PravinRanjan10** [sodafoundation/multi-cloud#1270]
**Issue/Feature Description:**

This isssues is for CRUD API pr. Some more optimization and validations can be added

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

1. Make  some functions in utils to validate duplicate backends. Avoid same code in multiple places.
2. why not there is an API for getTierID()? This can be used later in some other part of code too. And once you have the ID, GET Tier API can be called #

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by PravinRanjan10** [comment]
CRUD API pr #1269

**Comment by rajat-soda** [comment]
Code merged , to be closed.
