### ISSUE TITLE
AccessKey , SecretKey to be created from API

### ISSUE THREAD

**Issue by rajat-soda** [sodafoundation/multi-cloud#1272]
**Issue/Feature Description:**
AccessKey , SecretKey to be created from API - To enable users to create AKSK from the API , rather than the UI. 
AkSk from API will enable users to create the AKSK from the API and integrate to their Clients. 

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
AkSk from API will enable users to create the AKSK from the API and integrate to their Clients. 

**How to reproduce, in case of a bug:**
N/A

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by rajat-soda** [comment]
Create the AKSK in Multicloud rather than the API repo

**Comment by rajat-soda** [comment]
PR : https://github.com/sodafoundation/multi-cloud/pull/1275

**Comment by kumarashit** [comment]
Currently, who is going to consume it? If this is future, why should we make it part of multicloud?

**Comment by rajat-soda** [comment]
> Currently, who is going to consume it? If this is future, why should we make it part of multicloud?

No, AKSK is not being integrated with dashboard for J Rel.
its for any users who want to integrate SODA with their clients
