### ISSUE TITLE
[Testing RC1 - v1.3.1] Alibaba cloud issues

### ISSUE THREAD

**Issue by vineela1999** [sodafoundation/multi-cloud#1278]
**Issue/Feature Description:**

-  Error is getting displayed when trying to download an object of alibaba cloud bucket
- When trying to migrate from alibaba cloud bucket to any other cloud bucket ,objects are getting deleted from alibaba bucket but not getting uploaded in the destination cloud bucket.

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**for download object issue:**
1. Register an alibaba backend with valid credentials.
2. Go to Resource Manager -> Buckets -> Create Bucket
3. Create a bucket with alibaba backend
4. Upload an object in alibaba bucket
5. try to download the object then error is displayed

**for migration error check:**
1.Login to dashboard
2.Register alibaba and aws(any cloud) backend with valid credentials.
3.Go to Resource Manager -> Buckets -> Create Bucket
4 create a bucket with alibaba backend
5. create a bucket with AWS cloud backend
6. create an object in alibaba bucket
7. now migrate alibaba bucket with destination bucket with delete source objects enabled

Objects are not not getting uploaded in destination bucket

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**
**Error displayed in dashboard when trying to download object of alibaba cloud**
![Screenshot from 2021-06-26 11-43-25](https://user-images.githubusercontent.com/65920384/123504152-34c86c80-d675-11eb-895d-b07833fbfa65.png)
**Log from S3 API container (serving on 8090 port)**
![Screenshot from 2021-06-26 11-44-25](https://user-images.githubusercontent.com/65920384/123504154-35f99980-d675-11eb-8509-36473fc63cd5.png)
**alibaba bucket objects before migration:**
![Screenshot from 2021-06-26 11-47-49](https://user-images.githubusercontent.com/65920384/123504156-372ac680-d675-11eb-8a26-447f319e9584.png)
**aws bucket objects before migration:**
![Screenshot from 2021-06-26 11-48-02](https://user-images.githubusercontent.com/65920384/123504158-37c35d00-d675-11eb-9d49-a65c4cfb049c.png)
**migration with delete objects enabled:**
![Screenshot from 2021-06-26 11-48-21](https://user-images.githubusercontent.com/65920384/123504160-38f48a00-d675-11eb-8dc5-4c07cf85842c.png)
**migration successful message:**
![Screenshot from 2021-06-26 11-48-25](https://user-images.githubusercontent.com/65920384/123504162-3a25b700-d675-11eb-9525-e2851d5d975e.png)
**Alibaba bucket after migration:(objects of bucket are deleted)**
![Screenshot from 2021-06-26 11-48-32](https://user-images.githubusercontent.com/65920384/123504163-3b56e400-d675-11eb-82bd-53ec9e8c7d3c.png)
**Aws bucket after migration:(objects of alibaba are not inserted)**
![Screenshot from 2021-06-26 11-48-38](https://user-images.githubusercontent.com/65920384/123504165-3c881100-d675-11eb-874f-a667035dd092.png)

**Comment by rajat-soda** [comment]
Looks like a one off case , can be verified in RC2 rel and closed if does not occur again.

**Comment by PravinRanjan10** [comment]
Not producable. Closing
