### ISSUE TITLE
[SODACODE-2022] Manual buckets not required before backend registration for all cloud vendors now. List need updation

### ISSUE THREAD

**Issue by PravinRanjan10** [sodafoundation/multi-cloud#1309]
**Issue/Feature Description:**

In previous releases, Manual buckets were required for backend registration. Now from Isebela release onwards, buckets cretion is fully atomated from SODA.

What to change ??

1. go to this link https://docs.sodafoundation.io/guides/user-guides/multi-cloud/object-lifecycle-management/
2. Under this section: Create new backend using remote cloud bucket
3. update the Note section:

Note:
For cloud vendors like AWS, Azure, Huawei and GCP remote cloud buckets need not be created manually by user prior to backend registration. Remote cloud buckets can be created from SODA for these cloud vendors

To

Register a cloud backends as follows

4. Remove this line and below diagram from documentation

![Hack-1](https://user-images.githubusercontent.com/41313813/134611909-235fa6f8-5d36-492e-98c5-34b24b8bd552.png)

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by ampawar30** [comment]
PR Link: https://github.com/sodafoundation/documentation/pull/179
cc @PravinRanjan10  @anvithks

**Comment by PravinRanjan10** [comment]
Closing as docs are updated
