### ISSUE TITLE
Unable to create a bucket from SODA Dashboard when using Storage Service plans and logged in as non-admin user 

### ISSUE THREAD

**Issue by anvithks** [sodafoundation/multi-cloud#1311]
**Issue/Feature Description:**
When a non-admin user attempts to create a bucket from the SODA Dashboard the `Storage Service Plans` dropdown is greyed out.
![image](https://user-images.githubusercontent.com/19162717/136012159-b2283fd0-919d-4b7a-84a3-f033b7b4dabc.png)

The API call for GET tiers (storage service plans) is failing with an error as follows:

![image](https://user-images.githubusercontent.com/19162717/136012268-c27f73f8-081a-4710-a286-35182d7bc8b8.png)

![image](https://user-images.githubusercontent.com/19162717/136012247-dae21047-4d10-4cc5-a76e-672a7d2f0d75.png)

In the above case, the tenant1 was created and user1 was added to tenant1. tenant1 was added to Storage Service Plan SP1.
![image](https://user-images.githubusercontent.com/19162717/136012418-68826824-9eed-4d5e-814c-afe6c4fe908f.png)

![image](https://user-images.githubusercontent.com/19162717/136012423-f0139d87-8903-4664-99f3-c911804d64be.png)

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
If the non-admin user is unable to create a bucket then they will be unable to use the multi-cloud features of SODA.

**How to reproduce, in case of a bug:**
1. Log in to SODA Dashboard as admin user.
2. Register a cloud storage backend on the home page.
3. Create a tenant `tenant1`.
4. Create an user `user1` and add to `tenant1`
5. Go to Storage Service Plans page and click on `Create Service Plan`
6. Create a new Service Plan and select the tenant and the backend to add.
7. Logout from SODA Dashboard.
8. Login as `user1`.
9. Generate the AK/SK.
10. Go to `Resource Manager -> Buckets` and click on `Create`.
11. In the panel the Service Plans dropdown appears greyed out.

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by PravinRanjan10** [comment]
Closing as code is merged.
