### ISSUE TITLE
this is my first issue( do not merge)

### ISSUE THREAD

**Issue by arnoldprakash** [sodafoundation/multi-cloud#1330]
**Issue/Feature Description:**

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by PravinRanjan10** [comment]
#SODACODE-Issue-Rejected
(duplicate)
