### ISSUE TITLE
change name of multicloud as strato

### ISSUE THREAD

**Issue by Cpriya-123** [sodafoundation/multi-cloud#1331]
**multicloud name should be strato/Feature Description:**

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by PravinRanjan10** [comment]
#SODACODE-Issue-Rejected
(duplicate)
