### ISSUE TITLE
multi-cloud should be named as strato

### ISSUE THREAD

**Issue by vidyadharpai** [sodafoundation/multi-cloud#1335]
**Issue/Feature Description:**

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by PravinRanjan10** [comment]
#SODACODE-Issue-Rejected
(duplicate)
