### ISSUE TITLE
Reading package lists... Done Building dependency tree Reading state information... Done Package git is not available, but is referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source

### ISSUE THREAD

**Issue by Sachinkgowda** [sodafoundation/multi-cloud#1340]
**Issue/Feature Description:**

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by PravinRanjan10** [comment]
Issues is not clear
