### ISSUE TITLE
Multi-cloud installation guide should be separate 

### ISSUE THREAD

**Issue by PravinRanjan10** [sodafoundation/multi-cloud#1342]
**Issue/Feature Description:**
Currently all projects installation guide is combined. Which creates confusion.

So we can start separating the installation script to project specific

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by hari-govind** [comment]
Hi, I would like to work on this.
