### ISSUE TITLE
List metadata related issues

### ISSUE THREAD

**Issue by PravinRanjan10** [sodafoundation/multi-cloud#1392]
**Issue/Feature Description:**
Found few issues during testing of list metadata:

- [ ]  Log is not required to list all metadata
![log_for_result](https://user-images.githubusercontent.com/41313813/215967644-044ce60e-dfd6-438c-a0e2-94abd10c2a17.png)

- [ ] Please correct params name:
 "buckets": [
            {
                "creationDate": "2023-01-17 07:19:23 +0000 UTC",
                "name": "ap-south-1",
                "region": "ap-south-1",
                "numberOfObjects": 3,
                "totalSizeInBytes": 9443502,   ====> bucketSizeInBytes.
                                                                ====> ??(for filtered/queried buckect size)
                "objects": [
                    {
                        "lastModifiedDate": "2022-12-20 12:49:14 +0000 UTC",
                        "name": "3mb SVG.svg",
                        "bucketName": "ap-south-1",
                        "sizeInBytes": 3147834,     =====> objectSizeInBytes
                        "type": "binary/octet-stream",
                        "expiresDate": "0001-01-01 00:00:00 +0000 UTC"
                    },
                    {

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by PravinRanjan10** [comment]
@josephjacobmorris Please take a look

**Comment by josephjacobmorris** [comment]
@PravinRanjan10  assign the issue to me

**Comment by devanshjain7** [comment]
I found some issues while testing ListMetadata API:

1. ListMetadata (without any additional params) does not list buckets with zero objects.
2. Object Level filter param query (objectName/sizeOfObject) lists other buckets without that object too.
3. Giving cloud type param in request returns error “Not a valid AWS-S3 region”. Instead it should list all backend metadata of aws-s3 type.

Also you may display backend id field while listing metadata.

**Comment by josephjacobmorris** [comment]
raised PR for issues
1.Log is not required to list all metadata
2.Giving cloud type param in request returns error “Not a valid AWS-S3 region”. Instead it should list all backend metadata of aws-s3 type
https://github.com/sodafoundation/multi-cloud/pull/1393

**Comment by PravinRanjan10** [comment]
Fixed with #1396
