### ISSUE TITLE
issues about lifecycle 

### ISSUE THREAD

**Issue by xiangrumei** [sodafoundation/multi-cloud#158]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
we click the disable button , it doesn't work.
when we create transition and delete rules, transition rules work,delete rules don't work.
**What you expected to happen**:
we click the disable button, the function disabled.
when we create transition and delete rules,delete rules work.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sfzeng** [comment]
Fixed, see https://github.com/sodafoundation/multi-cloud/pull/159.
