### ISSUE TITLE
api crashed when I upload object

### ISSUE THREAD

**Issue by sfzeng** [sodafoundation/multi-cloud#183]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
I tried to upload an object more than 16MB, and api service crashed:
![dashboard](https://user-images.githubusercontent.com/38932432/64919915-54194100-d7e3-11e9-9087-5c432863a255.png)
![log](https://user-images.githubusercontent.com/38932432/64919916-59768b80-d7e3-11e9-9dd9-179d10172bbf.png)

**What you expected to happen**:
api service runs normally.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by PravinRanjan10** [comment]
It's already fixed. So closing
