### ISSUE TITLE
S3 APIs are not AWS S3 compatible.

### ISSUE THREAD

**Issue by sfzeng** [sodafoundation/multi-cloud#893]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
Two parts:
1. Currently, the URL of S3 APIs is like http(s)://ip:port/v1/s3/bucketname, which is not compatible with AWS S3, v1/s3/ should be removed.
At the same time, the authentification used a private algorithm, which is not compatible with AWS S3 too.
2. Each s3 API did not do AWS s3 compatilbe test, they may not be AWS S3 compatible.

Because of the above reasons, the third party s3 client, like the s3 browser, cannot be used to test multi-cloud.

**What you expected to happen**:
The third-party s3 client, like the s3 browser, cannot be used to test multi-cloud.

**How to reproduce it (as minimally and precisely as possible)**:
NA

**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kumarashit** [comment]
Closing
