### ISSUE TITLE
Failed to download Object from Bucket [Just vertify.]

### ISSUE THREAD

**Issue by Click2Cloud-Gamma** [sodafoundation/multi-cloud#906]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
1.Create a bucket.
Upload a *.txt, *.pptx, *.exe, *.docs files.
Download failed and got the error message as below:
![image](https://user-images.githubusercontent.com/45617130/77142340-d261e300-6aa5-11ea-9202-4129e41db427.png)
![image](https://user-images.githubusercontent.com/45617130/77142354-da218780-6aa5-11ea-9ed2-66338708faee.png)
![image](https://user-images.githubusercontent.com/45617130/77142413-02a98180-6aa6-11ea-82f3-fe076c269d51.png)
![image](https://user-images.githubusercontent.com/45617130/77142428-13f28e00-6aa6-11ea-8b74-e5c351e494df.png)
![image](https://user-images.githubusercontent.com/45617130/77142457-2cfb3f00-6aa6-11ea-9123-e2aafd1de440.png)

**How to reproduce it (as minimally and precisely as possible)**:
Follow the steps described above.
**Anything else we need to know?**:
According to my test, it seems jgp, png,mp4 files works fine.

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kumarashit** [comment]
I tried downloading object from AWS S3 and it worked. Can you please attach the api log?

**Comment by himanshuvar** [comment]
I am able to upload & download the object using AWS cloud vendor through POSTMAN. Please check the below snapshots.
![image](https://user-images.githubusercontent.com/8712951/79976878-fd7f8e00-84ba-11ea-9c4c-509138d3ae68.png)
![image](https://user-images.githubusercontent.com/8712951/79977175-6e26aa80-84bb-11ea-8d3e-d91102474a99.png)
![image](https://user-images.githubusercontent.com/8712951/79977356-c78ed980-84bb-11ea-8af5-1a9d0b0f6abe.png)

**Comment by himanshuvar** [comment]
I am able to upload and download .pdf, .ppt, .exe file to AWS using Daito release.

![image](https://user-images.githubusercontent.com/8712951/80202921-f9cb4300-8643-11ea-8918-ab0a7010e691.png)
![image](https://user-images.githubusercontent.com/8712951/80203089-39922a80-8644-11ea-9ecf-008b87823e61.png)

**Comment by Click2Cloud-Gamma** [comment]
@himanshuvar As I can see, the pdf was downloaded but it do not contain its contents, I have checked it for latest as well as daito release. Using Postman we get 200OK response but it does not content its contents.
![image](https://user-images.githubusercontent.com/45617130/80203709-39465f00-8645-11ea-9df3-4dbdca7444fb.png)

**Comment by subi9** [comment]
I can take this issue.

**Comment by PravinRanjan10** [comment]
Sure. Please go ahead for this issue.
@subi9

**Comment by subi9** [comment]
I have checked and its working fine.Here are the test results with the screenshots.
![Screenshot from 2022-04-22_1](https://user-images.githubusercontent.com/63897356/164882887-c14ce5be-b1a1-40a6-855b-ff9e93e7e850.png)
![Screenshot from 2022-04-22_2](https://user-images.githubusercontent.com/63897356/164882888-d28d755f-a2e0-4880-9b2f-a6426ccc2481.png)
![Screenshot from 2022-04-22_3](https://user-images.githubusercontent.com/63897356/164882892-6dc138f4-1cb4-41b4-aa59-6a777f5ac09d.png)
![Screenshot from 2022-04-22_4](https://user-images.githubusercontent.com/63897356/164882893-aa318e5e-dc8e-4cd0-8036-93c1a2e4d831.png)
![Screenshot from 2022-04-22_5](https://user-images.githubusercontent.com/63897356/164882895-048a7d10-35ee-4a50-a3c7-c2e0bab4f723.png)

**Comment by PravinRanjan10** [comment]
@subi9 Thank you for verifying.
LGTM
