### ISSUE TITLE
200 is returned when bucket is deleted successfully

### ISSUE THREAD

**Issue by sunfch** [sodafoundation/multi-cloud#915]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
send a delete bucket request, 200 is returned

**What you expected to happen**:
204 should be returned
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by PravinRanjan10** [comment]
@kumarashit please close this

**Comment by PravinRanjan10** [comment]
closing as code is merged in pr#909
