### ISSUE TITLE
500 Internal Error for GET, PUT, DELETE Backend for a non existing backend

### ISSUE THREAD

**Issue by himanshuvar** [sodafoundation/multi-cloud#932]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
> /kind bug

**What happened**: GET/PUT/DELETE Backends give 500 Internal Error for non-existing backend.

**What you expected to happen**: GET/PUT/DELETE Backends should give 404  for non-existing backend.

**How to reproduce it (as minimally and precisely as possible)**:
Update/Get/Delete for a non-existing backend.
<img width="699" alt="BackendGetIssuePOSTMAN" src="https://user-images.githubusercontent.com/8712951/81394211-3b2d1980-913f-11ea-9eb4-8f4561d29803.PNG">

**Error Logs:**

`[2020-05-08T14:26:00+05:30] [INFO] [/root/gopath/src/github.com/opensds/multi-cloud/backend/pkg/service/service.go] [service.(*backendService).GetBackend():71] [PID:1] Received GetBackend request.
2020/05/08 14:26:00 panic recovered: invalid input to ObjectIdHex: "5ea951d4553b0f000116be341"
2020/05/08 14:26:00 goroutine 253173 [running]:
runtime/debug.Stack(0x10e88a0, 0xc0001f4c00, 0x2)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/opensds/multi-cloud/vendor/github.com/micro/go-micro/server.(*rpcServer).accept.func1(0xc51e20, 0xc000380240)
        /root/gopath/src/github.com/opensds/multi-cloud/vendor/github.com/micro/go-micro/server/rpc_server.go:59 +0xe3
panic(0xa5ffc0, 0xc00036c620)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/opensds/multi-cloud/vendor/github.com/globalsign/mgo/bson.ObjectIdHex(0xc0004544c0, 0x19, 0xc0000d9500, 0x7fe753116d98)
        /root/gopath/src/github.com/opensds/multi-cloud/vendor/github.com/globalsign/mgo/bson/bson.go:212 +0x19c
github.com/opensds/multi-cloud/backend/pkg/db/drivers/mongo.(*mongoRepository).GetBackend(0x10c8e90, 0xc504e0, 0xc0001493e0, 0xc0004544c0, 0x19, 0x0, 0x0, 0x0)
        /root/gopath/src/github.com/opensds/multi-cloud/backend/pkg/db/drivers/mongo/mongo.go:142 +0xc8
github.com/opensds/multi-cloud/backend/pkg/service.(*backendService).GetBackend(0x10e88a0, 0xc504e0, 0xc0001493e0, 0xc00036c600, 0xc00000e060, 0x49497c, 0xad75c0)
        /root/gopath/src/github.com/opensds/multi-cloud/backend/pkg/service/service.go:72 +0xda
github.com/opensds/multi-cloud/backend/proto.(*backendHandler).GetBackend(0xc00001ff50, 0xc504e0, 0xc0001493e0, 0xc00036c600, 0xc00000e060, 0x7fe753116d98, 0x0)
        /root/gopath/src/github.com/opensds/multi-cloud/backend/proto/backend.micro.go:180 +0x5b
reflect.Value.call(0xc0000ba980, 0xc00000e2c0, 0x13, 0xb6394b, 0x4, 0xc000293580, 0x4, 0x4, 0xa89840, 0x0, ...)
        /usr/local/go/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0xc0000ba980, 0xc00000e2c0, 0x13, 0xc000293580, 0x4, 0x4, 0x40bda6, 0xc0001d0500, 0x40)
        /usr/local/go/src/reflect/value.go:321 +0xb4
github.com/opensds/multi-cloud/vendor/github.com/micro/go-micro/server.(*service).call.func1(0xc504e0, 0xc0001493e0, 0xc51d60, 0xc00014c3c0, 0xad75c0, 0xc00000e060, 0xc00000e060, 0x16)
        /root/gopath/src/github.com/opensds/multi-cloud/vendor/github.com/micro/go-micro/server/rpc_service.go:232 +0x278
github.com/opensds/multi-cloud/vendor/github.com/micro/go-micro/server.(*service).call(0xc0001fc680, 0xc504e0, 0xc0001493e0, 0xc00005b260, 0xc00019c390, 0xc0000d4510, 0xc0001f9200, 0xad7520, 0xc00036c600, 0x16, ...)
        /root/gopath/src/github.com/opensds/multi-cloud/vendor/github.com/micro/go-micro/server/rpc_service.go:247 +0x61e
github.com/opensds/multi-cloud/vendor/github.com/micro/go-micro/server.(*server).serveRequest(0xc00005b260, 0xc504e0, 0xc0001493e0, 0xc50720, 0xc000362cf0, 0xc000454400, 0x18, 0xc000362d50, 0x0)
        /root/gopath/src/github.com/opensds/multi-cloud/vendor/github.com/micro/go-micro/server/rpc_service.go:327 +0x283
github.com/opensds/multi-cloud/vendor/github.com/micro/go-micro/server.(*rpcServer).accept(0xc0000a08c0, 0xc51e20, 0xc000380240)
        /root/gopath/src/github.com/opensds/multi-cloud/vendor/github.com/micro/go-micro/server/rpc_server.go:114 +0x364
github.com/opensds/multi-cloud/vendor/github.com/micro/go-micro/transport.(*httpTransportListener).Accept.func1(0xc4e1e0, 0xc0002102a0, 0xc000216100)
        /root/gopath/src/github.com/opensds/multi-cloud/vendor/github.com/micro/go-micro/transport/http_transport.go:396 +0x1e1
net/http.HandlerFunc.ServeHTTP(0xc0001505c0, 0xc4e1e0, 0xc0002102a0, 0xc000216100)
        /usr/local/go/src/net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0xc000152280, 0xc4e1e0, 0xc0002102a0, 0xc000216100)
        /usr/local/go/src/net/http/server.go:2387 +0x1bd
github.com/opensds/multi-cloud/vendor/github.com/micro/h2c.(*HandlerH2C).ServeHTTP(0xc000150600, 0xc4e1e0, 0xc0002102a0, 0xc000216100)
        /root/gopath/src/github.com/opensds/multi-cloud/vendor/github.com/micro/h2c/h2c.go:85 +0x1e5
net/http.serverHandler.ServeHTTP(0xc000210000, 0xc4e1e0, 0xc0002102a0, 0xc000216100)
        /usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000087360, 0xc50460, 0xc000064140)
        /usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2927 +0x38e`
**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by amitdn2005** [comment]
Please assign to me
