### ISSUE TITLE
Migrate Multi-Cloud from dep to Go 1.11+ modules

### ISSUE THREAD

**Issue by himanshuvar** [sodafoundation/multi-cloud#939]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind feature

**What happened**:  Some packages are unable to update

**What you expected to happen**: Improved Dependency management

**How to reproduce it (as minimally and precisely as possible)**: 

**Anything else we need to know?**:

**Environment**:
- Gelato(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by skdwriting** [comment]
@sfzeng @himanshuvar the version Go 1.11+ is ok? How did we decide on this?
