### ISSUE TITLE
Backend, migration plans and job details get deleted after restarting datastore service

### ISSUE THREAD

**Issue by Click2cloud-Baheti** [sodafoundation/multi-cloud#957]
**Issue/Feature Description:**
MongoDB data is not retained in case service gets down
**Why this issue to fixed / feature is needed(give scenarios or use cases):**
If in any case, all the services gets down, then we again restart services (including datastore service), the mongodb data which contains backend information, migration plan details, lifecycle rule details, job details gets deleted. So data should retained after restarting datastore service also
**How to reproduce, in case of a bug:**
1. Create a backend --> Create bucket --> upload object [Successful]
2. run `docker-compose down` and `docker-compose up -d`
3. Try to upload object in same bucket --> FAILED (Backend does not exist)
**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**
Branch: `development`

**Comment by sfzeng** [comment]
It's fixed by [PR#958](https://github.com/sodafoundation/multi-cloud/pull/958)
