### ISSUE TITLE
Some information is confused when register backend.

### ISSUE THREAD

**Issue by robbieruan** [sodafoundation/multi-cloud#96]
When we register backend, we need input some information, like region, but it seems like that not all these information are necessary for all backend types, for example, region is not necessary for ceph. So can we make sure which information is necessary for each backend type, and let users just input those information, otherwise it would be confused.

**Comment by skdwriting** [comment]
adding to backlog.

**Comment by kumarashit** [comment]
@nguptaopensds  is it possible to get rid of region for all cloud providers?

**Comment by PravinRanjan10** [comment]
@kumarashit please close this

**Comment by PravinRanjan10** [comment]
Closing now
