### ISSUE TITLE
Bucket Creation is failing for a correct backend after a failed bucket creation for a non-existing backend

### ISSUE THREAD

**Issue by himanshuvar** [sodafoundation/multi-cloud#969]
**Issue/Feature Description:** Backend creation is failed through API but the entry is persisted in the database for a failed transaction for a non-existing backend. Because of this, the Bucket creation is failed even if the correct  backend details is provided.

**Why this issue to fixed / feature is needed(give scenarios or use cases):** This may be design & implementation issue for a cleaned bucket operation.

**How to reproduce, in case of a bug:**

1. PUT call for Bucket creation with Non-existing backend.
2. Create a backend.
3. PUT call for Bucket creation with above created backend.

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

Logs: 

`[2020-05-26T12:21:58+05:30] [ERROR] [/root/gopath/src/github.com/opensds/multi-cloud/s3/pkg/meta/db/drivers/tidb/client.go] [tidb.handleDBError():59] [PID:10] db error:Error 1062: Duplicate entry 'test' for key 'PRIMARY'

[2020-05-26T12:21:58+05:30] [ERROR] [/root/gopath/src/github.com/opensds/multi-cloud/s3/pkg/service/bucket.go] [service.(*s3Service).CreateBucket():127] [PID:10] Error creating SSE entry: DB error.
`

**Comment by sfzeng** [comment]
Hi, @himanshuvar Could you plz confirm which version you used? I followed the steps to reproduce the issue but failed, it works fine. See below:
![969_backend_not_exist](https://user-images.githubusercontent.com/38932432/84389297-6a481680-ac28-11ea-9884-ebcc379916c3.png)
![969_create_backend](https://user-images.githubusercontent.com/38932432/84389364-8350c780-ac28-11ea-8706-8af348ff88b9.png)
![969_put_bucket](https://user-images.githubusercontent.com/38932432/84389376-88157b80-ac28-11ea-9d84-edc27f85c8f4.png)

**Comment by himanshuvar** [comment]
@sfzeng I used development branch while facing/creating this issue.
I think the issue doesn't persist now.
Yes, You are right SSE configuration is not deleted.

**Comment by sfzeng** [comment]
Ok, thanks. @himanshuvar So I'm gona close thise issue.
