### ISSUE TITLE
Delete Volume API Support

### ISSUE THREAD

**Issue by himanshuvar** [sodafoundation/multi-cloud#979]
**Issue/Feature Description:** Delete the Volume from the DB associated to the backend in the multi-cloud

**Why this issue to fixed / feature is needed(give scenarios or use cases):** Supporting Block Service, This feature is required to delete the Volumes for an backend.
Delete API for Volume

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by PravinRanjan10** [comment]
code is merged in pr#1034
