### ISSUE TITLE
Get particular fileshare details from AWS

### ISSUE THREAD

**Issue by kumarashit** [sodafoundation/multi-cloud#990]
**Issue/Feature Description:**
API to get the share details from ShareId or Name
/v1/\<tenantId\>/Backend/\<backendId\>/share/\<shareId\>
**Why this issue to fixed / feature is needed(give scenarios or use cases):**
For making any operations on Share like putting ACL, adding/changing mount targets etc, user may need the Share details
**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by himanshuvar** [comment]
Done in https://github.com/sodafoundation/multi-cloud/pull/1032

**Comment by kumarashit** [comment]
Closing
