### ISSUE TITLE
Update the metadata or Tag of the Fileshare created in AWS

### ISSUE THREAD

**Issue by kumarashit** [sodafoundation/multi-cloud#991]
**Issue/Feature Description:**
API to update the fileshare properties
[PUT]v1/\<tenantId\>/Backend/\<backendId\>/shares/\<shareId\>
**Why this issue to fixed / feature is needed(give scenarios or use cases):**
User may need to update the share to change metadata/tags
**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by himanshuvar** [comment]
Done in https://github.com/sodafoundation/multi-cloud/pull/1032

**Comment by kumarashit** [comment]
Closing
