### ISSUE TITLE
Create Fileshare in Azure

### ISSUE THREAD

**Issue by kumarashit** [sodafoundation/multi-cloud#992]
**Issue/Feature Description:**
API to create Fileshare in Azure cloud
[POST] /v1/\<tenantId\>/Backend/\<backendId\>/shares
**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Filshares can be used to mount on the target and use it for host/application
**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by himanshuvar** [comment]
Done in https://github.com/sodafoundation/multi-cloud/pull/1032

**Comment by kumarashit** [comment]
Done
