### ISSUE TITLE
Get fileshare detail in Azure

### ISSUE THREAD

**Issue by kumarashit** [sodafoundation/multi-cloud#995]
**Issue/Feature Description:**
API to get the details of a particular
[GET] /v1/\<tenantId\>/Backend/\<backendId\>/shares/\<shareId\>
**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Get the details of a share which can used for different operations or updates
**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by himanshuvar** [comment]
Done in https://github.com/sodafoundation/multi-cloud/pull/1032

**Comment by kumarashit** [comment]
Done
